/*
 * Java domain class for entity "DatosAdicionalesRegularizaciones" 
 * Created on 2020-11-19 ( Date ISO 2020-11-19 - Time 09:31:18 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package com.telefonica.entity;

import java.io.Serializable;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * Domain class for entity "DatosAdicionalesRegularizaciones"
 *
 * @author Telosys Tools Generator
 *
 */
public class DatosAdicionalesRegularizaciones implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    private String     id           ;
    private String     tipo         ;
    private String     idIncidencia ;
    private String     secSuperior  ;
    @JsonFormat(pattern="dd-MM-yyyy' 'HH:mm")
    private Date       fecha        ;
    private String     descripcion  ;
    private String     solicitante  ;
    private String     autorizador  ;
    private String     provincia    ;
    private String     eliminar     ;
    private Date       fechaRegistro ;
    private String     autor        ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public DatosAdicionalesRegularizaciones() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR "KEY FIELD(S)"
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR "DATA FIELDS"
    //----------------------------------------------------------------------
    public void setId( String id ) {
        this.id = id ;
    }
    public String getId() {
        return this.id;
    }

    public void setTipo( String tipo ) {
        this.tipo = tipo ;
    }
    public String getTipo() {
        return this.tipo;
    }

    public void setIdIncidencia( String idIncidencia ) {
        this.idIncidencia = idIncidencia ;
    }
    public String getIdIncidencia() {
        return this.idIncidencia;
    }

    public void setSecSuperior( String secSuperior ) {
        this.secSuperior = secSuperior ;
    }
    public String getSecSuperior() {
        return this.secSuperior;
    }

    public void setFecha( Date fecha ) {
        this.fecha = fecha ;
    }
    public Date getFecha() {
        return this.fecha;
    }

    public void setDescripcion( String descripcion ) {
        this.descripcion = descripcion ;
    }
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setSolicitante( String solicitante ) {
        this.solicitante = solicitante ;
    }
    public String getSolicitante() {
        return this.solicitante;
    }

    public void setAutorizador( String autorizador ) {
        this.autorizador = autorizador ;
    }
    public String getAutorizador() {
        return this.autorizador;
    }

    public void setProvincia( String provincia ) {
        this.provincia = provincia ;
    }
    public String getProvincia() {
        return this.provincia;
    }

    public void setEliminar( String eliminar ) {
        this.eliminar = eliminar ;
    }
    public String getEliminar() {
        return this.eliminar;
    }

    public void setFechaRegistro( Date fechaRegistro ) {
        this.fechaRegistro = fechaRegistro ;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }

    public void setAutor( String autor ) {
        this.autor = autor ;
    }
    public String getAutor() {
        return this.autor;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------

public String toString() { 
   return "DatosAdicionalesRegularizaciones  ["+
    						",id  ="+ id +
    						",tipo  ="+ tipo +
    						",idIncidencia  ="+ idIncidencia +
    						",secSuperior  ="+ secSuperior +
    						",fecha  ="+ fecha +
    						",descripcion  ="+ descripcion +
    						",solicitante  ="+ solicitante +
    						",autorizador  ="+ autorizador +
    						",provincia  ="+ provincia +
    						",eliminar  ="+ eliminar +
    						",fechaRegistro  ="+ fechaRegistro +
    						",autor  ="+ autor +
"]";

}
}
