/*
 * Java domain class for entity "listadoIncidenciasRegularizada" 
 * Created on 2020-11-18 ( Date ISO 2020-11-18 - Time 16:37:46 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package com.telefonica.entity;

import java.io.Serializable;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * Domain class for entity "listadoIncidenciasRegularizada"
 *
 * @author Telosys Tools Generator
 *
 */
public class listadoIncidenciasRegularizada implements Serializable {

	private static final long serialVersionUID = 1L;

	//----------------------------------------------------------------------
	// ENTITY PRIMARY KEY 
	//----------------------------------------------------------------------

	//----------------------------------------------------------------------
	// ENTITY DATA FIELDS 
	//----------------------------------------------------------------------    
	private String     tipo         ;
	private String     red          ;
	private String     equipo       ;
	private String     provincia    ;
	private String     id           ;
	private String     responsable  ;
	@JsonFormat(pattern="dd-MM-yyyy' 'HH:mm")
	private Date       fechaCreacion ;
	@JsonFormat(pattern="dd-MM-yyyy' 'HH:mm")
	private Date       fechaReparacion ;
	@JsonFormat(pattern="dd-MM-yyyy' 'HH:mm")
	private Date       fechaFranqueo ;
	@JsonFormat(pattern="dd-MM-yyyy' 'HH:mm")
	private Date       fechaCierre  ;
	private String     baCobreClientes ;
	private String     baCobreIndisponibilidadPonderada ;
	private String     baCobreDuracionPonderada ;
	private String     baCobreIndisponibilidad ;
	private String     baCobreDuracion ;
	private String     baFibraClientes ;
	private String     baFibraIndisponibilidadPonderada ;
	private String     baFibraDuracionPonderada ;
	private String     baFibraIndisponibilidad ;
	private String     baFibraDuracion ;
	private String     baClientes   ;
	private String     baIndisponibilidadPonderada ;
	private String     baDuracionPonderada ;
	private String     baIndisponibilidad ;
	private String     baDuracion   ;
	private String     tvCobreClientes ;
	private String     tvCobreIndisponibilidadPonderada ;
	private String     tvCobreDuracionPonderada ;
	private String     tvCobreIndisponibilidad ;
	private String     tvCobreDuracion ;
	private String     tvFibraClientes ;
	private String     tvFibraIndisponibilidadPonderada ;
	private String     tvFibraDuracionPonderada ;
	private String     tvFibraIndisponibilidad ;
	private String     tvFibraDuracion ;
	private String     tvClientes   ;
	private String     tvIndisponibilidadPonderada ;
	private String     tvDuracionPonderada ;
	private String     tvIndisponibilidad ;
	private String     tvDuracion   ;
	private String     vozCobreClientes ;
	private String     vozCobreIndisponibilidadPonderada ;
	private String     vozCobreDuracionPonderada ;
	private String     vozCobreIndisponibilidad ;
	private String     vozCobreDuracion ;
	private String     vozFibraClientes ;
	private String     vozFibraIndisponibilidadPonderada ;
	private String     vozFibraDuracionPonderada ;
	private String     vozFibraIndisponibilidad ;
	private String     vozFibraDuracion ;
	private String     vozClientes  ;
	private String     vozIndisponibilidadPonderada ;
	private String     vozDuracionPonderada ;
	private String     vozIndisponibilidad ;
	private String     vozDuracion  ;
	private String     mfeClientes  ;
	private String     mfeIndisponibilidadPonderada ;
	private String     mfeDuracionPonderada ;
	private String     mfeIndisponibilidad ;
	private String     mfeDuracion  ;
	private String     fq1          ;
	private String     fq2          ;
	private String     fq3          ;
	private String     fq4          ;
	private String     fq5          ;
	private String     fq6          ;
	private String     suministrador ;
	private String     tecnologia   ;
	private String     modelo       ;
	private String     tipoDeSintoma ;
	private String     faltaRepuesto ;
	private String     tiempoMetereologico ;
	@JsonFormat(pattern="dd-MM-yyyy' 'HH:mm")
	private Date       fecha        ;
	private String     causa        ;
	private String     causaIgri    ;
	private String     subcausaIgri ;
	private String     severidad    ;
	@JsonFormat(pattern="dd-MM-yyyy' 'HH:mm")
	private Date       aciFInicio   ;
	@JsonFormat(pattern="dd-MM-yyyy' 'HH:mm")
	private Date       aciFFin      ;
	private String     aciDescripcion ;
	private String     aciCausa     ;
	private String     aciSaf       ;
	private String     aciAnalisis  ;
	private String     aciSeveridad ;
	private String     aciLocalizacion ;
	private String     idProblema   ;
	private String     concatInc1   ;
	private String     concatIncAvePla ;
	private String     concatIncAvePla2 ;
	private String     redIncidencia ;
	private String     edificioDslam ;
	private String     supermasivas ;
	private String     estadoGestion ;
	private String     nebaFibraClientes ;
	private String     nebaFibraIndisponibilidad ;
	private String     nebaLocalClientes ;
	private String     nebaLocalIndisponibilidad ;
	private String     nebaCobreClientes ;
	private String     nebaCobreIndisponibilidad ;
	private String     nebaFibraDuracion ;
	private String     nebaLocalDuracion ;
	private String     nebaCobreDuracion ;

	//----------------------------------------------------------------------
	// ENTITY LINKS ( RELATIONSHIP )
	//----------------------------------------------------------------------

	//----------------------------------------------------------------------
	// CONSTRUCTOR(S)
	//----------------------------------------------------------------------
	public listadoIncidenciasRegularizada() {
		super();
	}

	//----------------------------------------------------------------------
	// GETTER & SETTER FOR "KEY FIELD(S)"
	//----------------------------------------------------------------------

	//----------------------------------------------------------------------
	// GETTERS & SETTERS FOR "DATA FIELDS"
	//----------------------------------------------------------------------
	public void setTipo( String tipo ) {
		this.tipo = tipo ;
	}
	public String getTipo() {
		return this.tipo;
	}

	public void setRed( String red ) {
		this.red = red ;
	}
	public String getRed() {
		return this.red;
	}

	public void setEquipo( String equipo ) {
		this.equipo = equipo ;
	}
	public String getEquipo() {
		return this.equipo;
	}

	public void setProvincia( String provincia ) {
		this.provincia = provincia ;
	}
	public String getProvincia() {
		return this.provincia;
	}

	public void setId( String id ) {
		this.id = id ;
	}
	public String getId() {
		return this.id;
	}

	public void setResponsable( String responsable ) {
		this.responsable = responsable ;
	}
	public String getResponsable() {
		return this.responsable;
	}

	public void setFechaCreacion( Date fechaCreacion ) {
		this.fechaCreacion = fechaCreacion ;
	}
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaReparacion( Date fechaReparacion ) {
		this.fechaReparacion = fechaReparacion ;
	}
	public Date getFechaReparacion() {
		return this.fechaReparacion;
	}

	public void setFechaFranqueo( Date fechaFranqueo ) {
		this.fechaFranqueo = fechaFranqueo ;
	}
	public Date getFechaFranqueo() {
		return this.fechaFranqueo;
	}

	public void setFechaCierre( Date fechaCierre ) {
		this.fechaCierre = fechaCierre ;
	}
	public Date getFechaCierre() {
		return this.fechaCierre;
	}

	public void setBaCobreClientes( String baCobreClientes ) {
		this.baCobreClientes = baCobreClientes ;
	}
	public String getBaCobreClientes() {
		return this.baCobreClientes;
	}

	public void setBaCobreIndisponibilidadPonderada( String baCobreIndisponibilidadPonderada ) {
		this.baCobreIndisponibilidadPonderada = baCobreIndisponibilidadPonderada ;
	}
	public String getBaCobreIndisponibilidadPonderada() {
		return this.baCobreIndisponibilidadPonderada;
	}

	public void setBaCobreDuracionPonderada( String baCobreDuracionPonderada ) {
		this.baCobreDuracionPonderada = baCobreDuracionPonderada ;
	}
	public String getBaCobreDuracionPonderada() {
		return this.baCobreDuracionPonderada;
	}

	public void setBaCobreIndisponibilidad( String baCobreIndisponibilidad ) {
		this.baCobreIndisponibilidad = baCobreIndisponibilidad ;
	}
	public String getBaCobreIndisponibilidad() {
		return this.baCobreIndisponibilidad;
	}

	public void setBaCobreDuracion( String baCobreDuracion ) {
		this.baCobreDuracion = baCobreDuracion ;
	}
	public String getBaCobreDuracion() {
		return this.baCobreDuracion;
	}

	public void setBaFibraClientes( String baFibraClientes ) {
		this.baFibraClientes = baFibraClientes ;
	}
	public String getBaFibraClientes() {
		return this.baFibraClientes;
	}

	public void setBaFibraIndisponibilidadPonderada( String baFibraIndisponibilidadPonderada ) {
		this.baFibraIndisponibilidadPonderada = baFibraIndisponibilidadPonderada ;
	}
	public String getBaFibraIndisponibilidadPonderada() {
		return this.baFibraIndisponibilidadPonderada;
	}

	public void setBaFibraDuracionPonderada( String baFibraDuracionPonderada ) {
		this.baFibraDuracionPonderada = baFibraDuracionPonderada ;
	}
	public String getBaFibraDuracionPonderada() {
		return this.baFibraDuracionPonderada;
	}

	public void setBaFibraIndisponibilidad( String baFibraIndisponibilidad ) {
		this.baFibraIndisponibilidad = baFibraIndisponibilidad ;
	}
	public String getBaFibraIndisponibilidad() {
		return this.baFibraIndisponibilidad;
	}

	public void setBaFibraDuracion( String baFibraDuracion ) {
		this.baFibraDuracion = baFibraDuracion ;
	}
	public String getBaFibraDuracion() {
		return this.baFibraDuracion;
	}

	public void setBaClientes( String baClientes ) {
		this.baClientes = baClientes ;
	}
	public String getBaClientes() {
		return this.baClientes;
	}

	public void setBaIndisponibilidadPonderada( String baIndisponibilidadPonderada ) {
		this.baIndisponibilidadPonderada = baIndisponibilidadPonderada ;
	}
	public String getBaIndisponibilidadPonderada() {
		return this.baIndisponibilidadPonderada;
	}

	public void setBaDuracionPonderada( String baDuracionPonderada ) {
		this.baDuracionPonderada = baDuracionPonderada ;
	}
	public String getBaDuracionPonderada() {
		return this.baDuracionPonderada;
	}

	public void setBaIndisponibilidad( String baIndisponibilidad ) {
		this.baIndisponibilidad = baIndisponibilidad ;
	}
	public String getBaIndisponibilidad() {
		return this.baIndisponibilidad;
	}

	public void setBaDuracion( String baDuracion ) {
		this.baDuracion = baDuracion ;
	}
	public String getBaDuracion() {
		return this.baDuracion;
	}

	public void setTvCobreClientes( String tvCobreClientes ) {
		this.tvCobreClientes = tvCobreClientes ;
	}
	public String getTvCobreClientes() {
		return this.tvCobreClientes;
	}

	public void setTvCobreIndisponibilidadPonderada( String tvCobreIndisponibilidadPonderada ) {
		this.tvCobreIndisponibilidadPonderada = tvCobreIndisponibilidadPonderada ;
	}
	public String getTvCobreIndisponibilidadPonderada() {
		return this.tvCobreIndisponibilidadPonderada;
	}

	public void setTvCobreDuracionPonderada( String tvCobreDuracionPonderada ) {
		this.tvCobreDuracionPonderada = tvCobreDuracionPonderada ;
	}
	public String getTvCobreDuracionPonderada() {
		return this.tvCobreDuracionPonderada;
	}

	public void setTvCobreIndisponibilidad( String tvCobreIndisponibilidad ) {
		this.tvCobreIndisponibilidad = tvCobreIndisponibilidad ;
	}
	public String getTvCobreIndisponibilidad() {
		return this.tvCobreIndisponibilidad;
	}

	public void setTvCobreDuracion( String tvCobreDuracion ) {
		this.tvCobreDuracion = tvCobreDuracion ;
	}
	public String getTvCobreDuracion() {
		return this.tvCobreDuracion;
	}

	public void setTvFibraClientes( String tvFibraClientes ) {
		this.tvFibraClientes = tvFibraClientes ;
	}
	public String getTvFibraClientes() {
		return this.tvFibraClientes;
	}

	public void setTvFibraIndisponibilidadPonderada( String tvFibraIndisponibilidadPonderada ) {
		this.tvFibraIndisponibilidadPonderada = tvFibraIndisponibilidadPonderada ;
	}
	public String getTvFibraIndisponibilidadPonderada() {
		return this.tvFibraIndisponibilidadPonderada;
	}

	public void setTvFibraDuracionPonderada( String tvFibraDuracionPonderada ) {
		this.tvFibraDuracionPonderada = tvFibraDuracionPonderada ;
	}
	public String getTvFibraDuracionPonderada() {
		return this.tvFibraDuracionPonderada;
	}

	public void setTvFibraIndisponibilidad( String tvFibraIndisponibilidad ) {
		this.tvFibraIndisponibilidad = tvFibraIndisponibilidad ;
	}
	public String getTvFibraIndisponibilidad() {
		return this.tvFibraIndisponibilidad;
	}

	public void setTvFibraDuracion( String tvFibraDuracion ) {
		this.tvFibraDuracion = tvFibraDuracion ;
	}
	public String getTvFibraDuracion() {
		return this.tvFibraDuracion;
	}

	public void setTvClientes( String tvClientes ) {
		this.tvClientes = tvClientes ;
	}
	public String getTvClientes() {
		return this.tvClientes;
	}

	public void setTvIndisponibilidadPonderada( String tvIndisponibilidadPonderada ) {
		this.tvIndisponibilidadPonderada = tvIndisponibilidadPonderada ;
	}
	public String getTvIndisponibilidadPonderada() {
		return this.tvIndisponibilidadPonderada;
	}

	public void setTvDuracionPonderada( String tvDuracionPonderada ) {
		this.tvDuracionPonderada = tvDuracionPonderada ;
	}
	public String getTvDuracionPonderada() {
		return this.tvDuracionPonderada;
	}

	public void setTvIndisponibilidad( String tvIndisponibilidad ) {
		this.tvIndisponibilidad = tvIndisponibilidad ;
	}
	public String getTvIndisponibilidad() {
		return this.tvIndisponibilidad;
	}

	public void setTvDuracion( String tvDuracion ) {
		this.tvDuracion = tvDuracion ;
	}
	public String getTvDuracion() {
		return this.tvDuracion;
	}

	public void setVozCobreClientes( String vozCobreClientes ) {
		this.vozCobreClientes = vozCobreClientes ;
	}
	public String getVozCobreClientes() {
		return this.vozCobreClientes;
	}

	public void setVozCobreIndisponibilidadPonderada( String vozCobreIndisponibilidadPonderada ) {
		this.vozCobreIndisponibilidadPonderada = vozCobreIndisponibilidadPonderada ;
	}
	public String getVozCobreIndisponibilidadPonderada() {
		return this.vozCobreIndisponibilidadPonderada;
	}

	public void setVozCobreDuracionPonderada( String vozCobreDuracionPonderada ) {
		this.vozCobreDuracionPonderada = vozCobreDuracionPonderada ;
	}
	public String getVozCobreDuracionPonderada() {
		return this.vozCobreDuracionPonderada;
	}

	public void setVozCobreIndisponibilidad( String vozCobreIndisponibilidad ) {
		this.vozCobreIndisponibilidad = vozCobreIndisponibilidad ;
	}
	public String getVozCobreIndisponibilidad() {
		return this.vozCobreIndisponibilidad;
	}

	public void setVozCobreDuracion( String vozCobreDuracion ) {
		this.vozCobreDuracion = vozCobreDuracion ;
	}
	public String getVozCobreDuracion() {
		return this.vozCobreDuracion;
	}

	public void setVozFibraClientes( String vozFibraClientes ) {
		this.vozFibraClientes = vozFibraClientes ;
	}
	public String getVozFibraClientes() {
		return this.vozFibraClientes;
	}

	public void setVozFibraIndisponibilidadPonderada( String vozFibraIndisponibilidadPonderada ) {
		this.vozFibraIndisponibilidadPonderada = vozFibraIndisponibilidadPonderada ;
	}
	public String getVozFibraIndisponibilidadPonderada() {
		return this.vozFibraIndisponibilidadPonderada;
	}

	public void setVozFibraDuracionPonderada( String vozFibraDuracionPonderada ) {
		this.vozFibraDuracionPonderada = vozFibraDuracionPonderada ;
	}
	public String getVozFibraDuracionPonderada() {
		return this.vozFibraDuracionPonderada;
	}

	public void setVozFibraIndisponibilidad( String vozFibraIndisponibilidad ) {
		this.vozFibraIndisponibilidad = vozFibraIndisponibilidad ;
	}
	public String getVozFibraIndisponibilidad() {
		return this.vozFibraIndisponibilidad;
	}

	public void setVozFibraDuracion( String vozFibraDuracion ) {
		this.vozFibraDuracion = vozFibraDuracion ;
	}
	public String getVozFibraDuracion() {
		return this.vozFibraDuracion;
	}

	public void setVozClientes( String vozClientes ) {
		this.vozClientes = vozClientes ;
	}
	public String getVozClientes() {
		return this.vozClientes;
	}

	public void setVozIndisponibilidadPonderada( String vozIndisponibilidadPonderada ) {
		this.vozIndisponibilidadPonderada = vozIndisponibilidadPonderada ;
	}
	public String getVozIndisponibilidadPonderada() {
		return this.vozIndisponibilidadPonderada;
	}

	public void setVozDuracionPonderada( String vozDuracionPonderada ) {
		this.vozDuracionPonderada = vozDuracionPonderada ;
	}
	public String getVozDuracionPonderada() {
		return this.vozDuracionPonderada;
	}

	public void setVozIndisponibilidad( String vozIndisponibilidad ) {
		this.vozIndisponibilidad = vozIndisponibilidad ;
	}
	public String getVozIndisponibilidad() {
		return this.vozIndisponibilidad;
	}

	public void setVozDuracion( String vozDuracion ) {
		this.vozDuracion = vozDuracion ;
	}
	public String getVozDuracion() {
		return this.vozDuracion;
	}

	public void setMfeClientes( String mfeClientes ) {
		this.mfeClientes = mfeClientes ;
	}
	public String getMfeClientes() {
		return this.mfeClientes;
	}

	public void setMfeIndisponibilidadPonderada( String mfeIndisponibilidadPonderada ) {
		this.mfeIndisponibilidadPonderada = mfeIndisponibilidadPonderada ;
	}
	public String getMfeIndisponibilidadPonderada() {
		return this.mfeIndisponibilidadPonderada;
	}

	public void setMfeDuracionPonderada( String mfeDuracionPonderada ) {
		this.mfeDuracionPonderada = mfeDuracionPonderada ;
	}
	public String getMfeDuracionPonderada() {
		return this.mfeDuracionPonderada;
	}

	public void setMfeIndisponibilidad( String mfeIndisponibilidad ) {
		this.mfeIndisponibilidad = mfeIndisponibilidad ;
	}
	public String getMfeIndisponibilidad() {
		return this.mfeIndisponibilidad;
	}

	public void setMfeDuracion( String mfeDuracion ) {
		this.mfeDuracion = mfeDuracion ;
	}
	public String getMfeDuracion() {
		return this.mfeDuracion;
	}

	public void setFq1( String fq1 ) {
		this.fq1 = fq1 ;
	}
	public String getFq1() {
		return this.fq1;
	}

	public void setFq2( String fq2 ) {
		this.fq2 = fq2 ;
	}
	public String getFq2() {
		return this.fq2;
	}

	public void setFq3( String fq3 ) {
		this.fq3 = fq3 ;
	}
	public String getFq3() {
		return this.fq3;
	}

	public void setFq4( String fq4 ) {
		this.fq4 = fq4 ;
	}
	public String getFq4() {
		return this.fq4;
	}

	public void setFq5( String fq5 ) {
		this.fq5 = fq5 ;
	}
	public String getFq5() {
		return this.fq5;
	}

	public void setFq6( String fq6 ) {
		this.fq6 = fq6 ;
	}
	public String getFq6() {
		return this.fq6;
	}

	public void setSuministrador( String suministrador ) {
		this.suministrador = suministrador ;
	}
	public String getSuministrador() {
		return this.suministrador;
	}

	public void setTecnologia( String tecnologia ) {
		this.tecnologia = tecnologia ;
	}
	public String getTecnologia() {
		return this.tecnologia;
	}

	public void setModelo( String modelo ) {
		this.modelo = modelo ;
	}
	public String getModelo() {
		return this.modelo;
	}

	public void setTipoDeSintoma( String tipoDeSintoma ) {
		this.tipoDeSintoma = tipoDeSintoma ;
	}
	public String getTipoDeSintoma() {
		return this.tipoDeSintoma;
	}

	public void setFaltaRepuesto( String faltaRepuesto ) {
		this.faltaRepuesto = faltaRepuesto ;
	}
	public String getFaltaRepuesto() {
		return this.faltaRepuesto;
	}

	public void setTiempoMetereologico( String tiempoMetereologico ) {
		this.tiempoMetereologico = tiempoMetereologico ;
	}
	public String getTiempoMetereologico() {
		return this.tiempoMetereologico;
	}

	public void setFecha( Date fecha ) {
		this.fecha = fecha ;
	}
	public Date getFecha() {
		return this.fecha;
	}

	public void setCausa( String causa ) {
		this.causa = causa ;
	}
	public String getCausa() {
		return this.causa;
	}

	public void setCausaIgri( String causaIgri ) {
		this.causaIgri = causaIgri ;
	}
	public String getCausaIgri() {
		return this.causaIgri;
	}

	public void setSubcausaIgri( String subcausaIgri ) {
		this.subcausaIgri = subcausaIgri ;
	}
	public String getSubcausaIgri() {
		return this.subcausaIgri;
	}

	public void setSeveridad( String severidad ) {
		this.severidad = severidad ;
	}
	public String getSeveridad() {
		return this.severidad;
	}

	public void setAciFInicio( Date aciFInicio ) {
		this.aciFInicio = aciFInicio ;
	}
	public Date getAciFInicio() {
		return this.aciFInicio;
	}

	public void setAciFFin( Date aciFFin ) {
		this.aciFFin = aciFFin ;
	}
	public Date getAciFFin() {
		return this.aciFFin;
	}

	public void setAciDescripcion( String aciDescripcion ) {
		this.aciDescripcion = aciDescripcion ;
	}
	public String getAciDescripcion() {
		return this.aciDescripcion;
	}

	public void setAciCausa( String aciCausa ) {
		this.aciCausa = aciCausa ;
	}
	public String getAciCausa() {
		return this.aciCausa;
	}

	public void setAciSaf( String aciSaf ) {
		this.aciSaf = aciSaf ;
	}
	public String getAciSaf() {
		return this.aciSaf;
	}

	public void setAciAnalisis( String aciAnalisis ) {
		this.aciAnalisis = aciAnalisis ;
	}
	public String getAciAnalisis() {
		return this.aciAnalisis;
	}

	public void setAciSeveridad( String aciSeveridad ) {
		this.aciSeveridad = aciSeveridad ;
	}
	public String getAciSeveridad() {
		return this.aciSeveridad;
	}

	public void setAciLocalizacion( String aciLocalizacion ) {
		this.aciLocalizacion = aciLocalizacion ;
	}
	public String getAciLocalizacion() {
		return this.aciLocalizacion;
	}

	public void setIdProblema( String idProblema ) {
		this.idProblema = idProblema ;
	}
	public String getIdProblema() {
		return this.idProblema;
	}

	public void setConcatInc1( String concatInc1 ) {
		this.concatInc1 = concatInc1 ;
	}
	public String getConcatInc1() {
		return this.concatInc1;
	}

	public void setConcatIncAvePla( String concatIncAvePla ) {
		this.concatIncAvePla = concatIncAvePla ;
	}
	public String getConcatIncAvePla() {
		return this.concatIncAvePla;
	}

	public void setConcatIncAvePla2( String concatIncAvePla2 ) {
		this.concatIncAvePla2 = concatIncAvePla2 ;
	}
	public String getConcatIncAvePla2() {
		return this.concatIncAvePla2;
	}

	public void setRedIncidencia( String redIncidencia ) {
		this.redIncidencia = redIncidencia ;
	}
	public String getRedIncidencia() {
		return this.redIncidencia;
	}

	public void setEdificioDslam( String edificioDslam ) {
		this.edificioDslam = edificioDslam ;
	}
	public String getEdificioDslam() {
		return this.edificioDslam;
	}

	public void setSupermasivas( String supermasivas ) {
		this.supermasivas = supermasivas ;
	}
	public String getSupermasivas() {
		return this.supermasivas;
	}

	public void setEstadoGestion( String estadoGestion ) {
		this.estadoGestion = estadoGestion ;
	}
	public String getEstadoGestion() {
		return this.estadoGestion;
	}

	public void setNebaFibraClientes( String nebaFibraClientes ) {
		this.nebaFibraClientes = nebaFibraClientes ;
	}
	public String getNebaFibraClientes() {
		return this.nebaFibraClientes;
	}

	public void setNebaFibraIndisponibilidad( String nebaFibraIndisponibilidad ) {
		this.nebaFibraIndisponibilidad = nebaFibraIndisponibilidad ;
	}
	public String getNebaFibraIndisponibilidad() {
		return this.nebaFibraIndisponibilidad;
	}

	public void setNebaLocalClientes( String nebaLocalClientes ) {
		this.nebaLocalClientes = nebaLocalClientes ;
	}
	public String getNebaLocalClientes() {
		return this.nebaLocalClientes;
	}

	public void setNebaLocalIndisponibilidad( String nebaLocalIndisponibilidad ) {
		this.nebaLocalIndisponibilidad = nebaLocalIndisponibilidad ;
	}
	public String getNebaLocalIndisponibilidad() {
		return this.nebaLocalIndisponibilidad;
	}

	public void setNebaCobreClientes( String nebaCobreClientes ) {
		this.nebaCobreClientes = nebaCobreClientes ;
	}
	public String getNebaCobreClientes() {
		return this.nebaCobreClientes;
	}

	public void setNebaCobreIndisponibilidad( String nebaCobreIndisponibilidad ) {
		this.nebaCobreIndisponibilidad = nebaCobreIndisponibilidad ;
	}
	public String getNebaCobreIndisponibilidad() {
		return this.nebaCobreIndisponibilidad;
	}

	public void setNebaFibraDuracion( String nebaFibraDuracion ) {
		this.nebaFibraDuracion = nebaFibraDuracion ;
	}
	public String getNebaFibraDuracion() {
		return this.nebaFibraDuracion;
	}

	public void setNebaLocalDuracion( String nebaLocalDuracion ) {
		this.nebaLocalDuracion = nebaLocalDuracion ;
	}
	public String getNebaLocalDuracion() {
		return this.nebaLocalDuracion;
	}

	public void setNebaCobreDuracion( String nebaCobreDuracion ) {
		this.nebaCobreDuracion = nebaCobreDuracion ;
	}
	public String getNebaCobreDuracion() {
		return this.nebaCobreDuracion;
	}


	//----------------------------------------------------------------------
	// GETTERS & SETTERS FOR LINKS
	//----------------------------------------------------------------------

	//----------------------------------------------------------------------
	// toString METHOD
	//----------------------------------------------------------------------
	public String toString() { 

		return "listadoIncidenciasRegularizada ["+
				"tipo  ="+     tipo         +
				",red  ="+     red          +
				",equipo="+     equipo       +
				",provincia  ="+     provincia    +
				",provincia  ="+     id           +
				", responsable ="+     responsable  +
				",fechaCreacion  ="+     fechaCreacion +
				",fechaReparacion  ="+      fechaReparacion +
				",fechaFranqueo  ="+       fechaFranqueo +
				",fechaCierre  ="+       fechaCierre  +
				",baCobreClientes  ="+     baCobreClientes +
				",baCobreIndisponibilidadPonderada  ="+     baCobreIndisponibilidadPonderada +
				", baCobreDuracionPonderada ="+     baCobreDuracionPonderada +
				",baCobreIndisponibilidad  ="+     baCobreIndisponibilidad +
				",baCobreDuracion  ="+     baCobreDuracion +
				", baFibraClientes ="+     baFibraClientes +
				",baFibraIndisponibilidadPonderada ="+     baFibraIndisponibilidadPonderada +
				", baFibraDuracionPonderada ="+     baFibraDuracionPonderada +
				",baFibraIndisponibilidad  ="+     baFibraIndisponibilidad +
				", baFibraDuracion ="+     baFibraDuracion +
				",baClientes  ="+     baClientes   +
				",baIndisponibilidadPonderada  ="+     baIndisponibilidadPonderada +
				",baDuracionPonderada  ="+     baDuracionPonderada +
				",baIndisponibilidad  ="+     baIndisponibilidad +
				",baDuracion  ="+     baDuracion   +
				", tvCobreClientes ="+     tvCobreClientes +
				", tvCobreIndisponibilidadPonderada ="+     tvCobreIndisponibilidadPonderada +
				", tvCobreDuracionPonderada ="+     tvCobreDuracionPonderada +
				", tvCobreIndisponibilidad ="+     tvCobreIndisponibilidad +
				", tvCobreDuracion ="+     tvCobreDuracion +
				", tvFibraClientes ="+     tvFibraClientes +
				", tvFibraIndisponibilidadPonderada ="+     tvFibraIndisponibilidadPonderada +
				", tvFibraDuracionPonderada ="+     tvFibraDuracionPonderada +
				", tvFibraIndisponibilidad ="+     tvFibraIndisponibilidad +
				",tvFibraDuracion  ="+     tvFibraDuracion +
				", tvClientes ="+     tvClientes   +
				",tvIndisponibilidadPonderada  ="+     tvIndisponibilidadPonderada +
				", tvDuracionPonderada ="+     tvDuracionPonderada +
				", tvIndisponibilidad ="+     tvIndisponibilidad +
				", tvDuracion ="+     tvDuracion   +
				", vozCobreClientes ="+     vozCobreClientes +
				", vozCobreIndisponibilidadPonderada ="+     vozCobreIndisponibilidadPonderada +
				", vozCobreDuracionPonderada ="+     vozCobreDuracionPonderada +
				", vozCobreIndisponibilidad ="+     vozCobreIndisponibilidad +
				", vozCobreDuracion ="+     vozCobreDuracion +
				", vozFibraClientes ="+     vozFibraClientes +
				", vozFibraIndisponibilidadPonderada ="+     vozFibraIndisponibilidadPonderada +
				", vozFibraDuracionPonderada ="+     vozFibraDuracionPonderada +
				", vozFibraIndisponibilidad ="+     vozFibraIndisponibilidad +
				", vozFibraDuracion ="+     vozFibraDuracion +
				", vozClientes ="+     vozClientes  +
				", vozIndisponibilidadPonderada="+     vozIndisponibilidadPonderada +
				", vozDuracionPonderada ="+     vozDuracionPonderada +
				", vozIndisponibilidad ="+     vozIndisponibilidad +
				",vozDuracion  ="+     vozDuracion  +
				", mfeClientes ="+     mfeClientes  +
				", mfeIndisponibilidadPonderada ="+     mfeIndisponibilidadPonderada +
				", mfeDuracionPonderada ="+     mfeDuracionPonderada +
				", mfeIndisponibilidad ="+     mfeIndisponibilidad +
				", mfeDuracion  ="+     mfeDuracion  +
				", fq1 ="+     fq1          +
				", fq2 ="+     fq2          +
				", fq3 ="+     fq3          +
				", fq4 ="+     fq4          +
				", fq5 ="+     fq5          +
				", fq6 ="+     fq6          +
				",  suministrador="+     suministrador +
				", tecnologia ="+     tecnologia   +
				", modelo ="+     modelo       +
				", tipoDeSintoma ="+     tipoDeSintoma +
				",  faltaRepuesto="+     faltaRepuesto +
				", tiempoMetereologico ="+     tiempoMetereologico +
				",  fecha="+     fecha        +
				", causa ="+     causa        +
				", causaIgri ="+     causaIgri    +
				", subcausaIgri ="+     subcausaIgri +
				",  severidad="+     severidad    +
				",  aciFInicio="+     aciFInicio   +
				", aciFFin ="+     aciFFin      +
				", aciDescripcion ="+     aciDescripcion +
				", aciCausa ="+     aciCausa     +
				", aciSaf ="+     aciSaf       +
				", aciAnalisis ="+     aciAnalisis  +
				", aciSeveridad ="+     aciSeveridad +
				",  aciLocalizacion="+     aciLocalizacion +
				",  idProblema="+     idProblema   +
				",  concatInc1="+     concatInc1   +
				",  concatIncAvePla="+     concatIncAvePla +
				", concatIncAvePla2 ="+     concatIncAvePla2 +
				",  redIncidencia="+     redIncidencia +
				",edificioDslam  ="+     edificioDslam +
				",supermasivas  ="+     supermasivas +
				", estadoGestion ="+     estadoGestion +
				", nebaFibraClientes ="+     nebaFibraClientes +
				",nebaFibraIndisponibilidad  ="+     nebaFibraIndisponibilidad +
				",nebaLocalClientes  ="+     nebaLocalClientes +
				", nebaLocalIndisponibilidad ="+     nebaLocalIndisponibilidad +
				",nebaCobreClientes  ="+     nebaCobreClientes +
				", nebaCobreIndisponibilidad ="+     nebaCobreIndisponibilidad +
				",nebaLocalDuracion  ="+     nebaLocalDuracion +
				", nebaLocalDuracion ="+     nebaLocalDuracion +
				", nebaCobreDuracion ="+     nebaCobreDuracion +"]";
	} 

}
