/*
 * Java domain class for entity "ListadoIncidenciasDisponibilidadLlamadasRegularizada" 
 * Created on 2020-11-19 ( Date ISO 2020-11-19 - Time 09:28:19 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package com.telefonica.entity;

import java.io.Serializable;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * Domain class for entity "ListadoIncidenciasDisponibilidadLlamadasRegularizada"
 *
 * @author Telosys Tools Generator
 *
 */
public class ListadoIncidenciasDisponibilidadLlamadasRegularizada implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
   
    @JsonFormat(pattern="dd-MM-yyyy' 'HH:mm")
    private Date       fecha        ;
    private String     secSuperior  ;
    private String     provincia    ;
    private String     tipo         ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    private String     datosCobre   ;
    private String     datosFibra   ;
    private String     voz          ;
    private String     vozIp        ;
    private String     tvCobre      ;
    private String     tvFibra      ;
    private String     tv           ;
    private String     mfe          ;
    private String     dth          ;
    private String     ott          ;
    private String     netflix      ;
    private String     disney       ;
    private String     clieDatosCobre ;
    private String     clieDatosFibra ;
    private String     clieVoz      ;
    private String     clieVozIp    ;
    private String     clieTvCobre  ;
    private String     clieTvFibra  ;
    private String     clieTv       ;
    private String     clieMfe      ;
    private String     clieDth      ;
    private String     clieOtt      ;
    private String     clieNetflix  ;
    private String     clieDisney   ;
    private String     duracionDatosCobre ;
    private String     duracionDatosFibra ;
    private String     duracionVoz  ;
    private String     duracionVozIp ;
    private String     duracionTvCobre ;
    private String     duracionTvFibra ;
    private String     duracionTv   ;
    private String     duracionMfe  ;
    private String     duracionDth  ;
    private String     duracionOtt  ;
    private String     duracionNetflix ;
    private String     duracionDisney ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ListadoIncidenciasDisponibilidadLlamadasRegularizada() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR "KEY FIELD(S)"
    //----------------------------------------------------------------------
    public void setFecha( Date fecha ) {
        this.fecha = fecha ;
    }
    public Date getFecha() {
        return this.fecha;
    }

    public void setSecSuperior( String secSuperior ) {
        this.secSuperior = secSuperior ;
    }
    public String getSecSuperior() {
        return this.secSuperior;
    }

    public void setProvincia( String provincia ) {
        this.provincia = provincia ;
    }
    public String getProvincia() {
        return this.provincia;
    }

    public void setTipo( String tipo ) {
        this.tipo = tipo ;
    }
    public String getTipo() {
        return this.tipo;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR "DATA FIELDS"
    //----------------------------------------------------------------------
    public void setDatosCobre( String datosCobre ) {
        this.datosCobre = datosCobre ;
    }
    public String getDatosCobre() {
        return this.datosCobre;
    }

    public void setDatosFibra( String datosFibra ) {
        this.datosFibra = datosFibra ;
    }
    public String getDatosFibra() {
        return this.datosFibra;
    }

    public void setVoz( String voz ) {
        this.voz = voz ;
    }
    public String getVoz() {
        return this.voz;
    }

    public void setVozIp( String vozIp ) {
        this.vozIp = vozIp ;
    }
    public String getVozIp() {
        return this.vozIp;
    }

    public void setTvCobre( String tvCobre ) {
        this.tvCobre = tvCobre ;
    }
    public String getTvCobre() {
        return this.tvCobre;
    }

    public void setTvFibra( String tvFibra ) {
        this.tvFibra = tvFibra ;
    }
    public String getTvFibra() {
        return this.tvFibra;
    }

    public void setTv( String tv ) {
        this.tv = tv ;
    }
    public String getTv() {
        return this.tv;
    }

    public void setMfe( String mfe ) {
        this.mfe = mfe ;
    }
    public String getMfe() {
        return this.mfe;
    }

    public void setDth( String dth ) {
        this.dth = dth ;
    }
    public String getDth() {
        return this.dth;
    }

    public void setOtt( String ott ) {
        this.ott = ott ;
    }
    public String getOtt() {
        return this.ott;
    }

    public void setNetflix( String netflix ) {
        this.netflix = netflix ;
    }
    public String getNetflix() {
        return this.netflix;
    }

    public void setDisney( String disney ) {
        this.disney = disney ;
    }
    public String getDisney() {
        return this.disney;
    }

    public void setClieDatosCobre( String clieDatosCobre ) {
        this.clieDatosCobre = clieDatosCobre ;
    }
    public String getClieDatosCobre() {
        return this.clieDatosCobre;
    }

    public void setClieDatosFibra( String clieDatosFibra ) {
        this.clieDatosFibra = clieDatosFibra ;
    }
    public String getClieDatosFibra() {
        return this.clieDatosFibra;
    }

    public void setClieVoz( String clieVoz ) {
        this.clieVoz = clieVoz ;
    }
    public String getClieVoz() {
        return this.clieVoz;
    }

    public void setClieVozIp( String clieVozIp ) {
        this.clieVozIp = clieVozIp ;
    }
    public String getClieVozIp() {
        return this.clieVozIp;
    }

    public void setClieTvCobre( String clieTvCobre ) {
        this.clieTvCobre = clieTvCobre ;
    }
    public String getClieTvCobre() {
        return this.clieTvCobre;
    }

    public void setClieTvFibra( String clieTvFibra ) {
        this.clieTvFibra = clieTvFibra ;
    }
    public String getClieTvFibra() {
        return this.clieTvFibra;
    }

    public void setClieTv( String clieTv ) {
        this.clieTv = clieTv ;
    }
    public String getClieTv() {
        return this.clieTv;
    }

    public void setClieMfe( String clieMfe ) {
        this.clieMfe = clieMfe ;
    }
    public String getClieMfe() {
        return this.clieMfe;
    }

    public void setClieDth( String clieDth ) {
        this.clieDth = clieDth ;
    }
    public String getClieDth() {
        return this.clieDth;
    }

    public void setClieOtt( String clieOtt ) {
        this.clieOtt = clieOtt ;
    }
    public String getClieOtt() {
        return this.clieOtt;
    }

    public void setClieNetflix( String clieNetflix ) {
        this.clieNetflix = clieNetflix ;
    }
    public String getClieNetflix() {
        return this.clieNetflix;
    }

    public void setClieDisney( String clieDisney ) {
        this.clieDisney = clieDisney ;
    }
    public String getClieDisney() {
        return this.clieDisney;
    }

    public void setDuracionDatosCobre( String duracionDatosCobre ) {
        this.duracionDatosCobre = duracionDatosCobre ;
    }
    public String getDuracionDatosCobre() {
        return this.duracionDatosCobre;
    }

    public void setDuracionDatosFibra( String duracionDatosFibra ) {
        this.duracionDatosFibra = duracionDatosFibra ;
    }
    public String getDuracionDatosFibra() {
        return this.duracionDatosFibra;
    }

    public void setDuracionVoz( String duracionVoz ) {
        this.duracionVoz = duracionVoz ;
    }
    public String getDuracionVoz() {
        return this.duracionVoz;
    }

    public void setDuracionVozIp( String duracionVozIp ) {
        this.duracionVozIp = duracionVozIp ;
    }
    public String getDuracionVozIp() {
        return this.duracionVozIp;
    }

    public void setDuracionTvCobre( String duracionTvCobre ) {
        this.duracionTvCobre = duracionTvCobre ;
    }
    public String getDuracionTvCobre() {
        return this.duracionTvCobre;
    }

    public void setDuracionTvFibra( String duracionTvFibra ) {
        this.duracionTvFibra = duracionTvFibra ;
    }
    public String getDuracionTvFibra() {
        return this.duracionTvFibra;
    }

    public void setDuracionTv( String duracionTv ) {
        this.duracionTv = duracionTv ;
    }
    public String getDuracionTv() {
        return this.duracionTv;
    }

    public void setDuracionMfe( String duracionMfe ) {
        this.duracionMfe = duracionMfe ;
    }
    public String getDuracionMfe() {
        return this.duracionMfe;
    }

    public void setDuracionDth( String duracionDth ) {
        this.duracionDth = duracionDth ;
    }
    public String getDuracionDth() {
        return this.duracionDth;
    }

    public void setDuracionOtt( String duracionOtt ) {
        this.duracionOtt = duracionOtt ;
    }
    public String getDuracionOtt() {
        return this.duracionOtt;
    }

    public void setDuracionNetflix( String duracionNetflix ) {
        this.duracionNetflix = duracionNetflix ;
    }
    public String getDuracionNetflix() {
        return this.duracionNetflix;
    }

    public void setDuracionDisney( String duracionDisney ) {
        this.duracionDisney = duracionDisney ;
    }
    public String getDuracionDisney() {
        return this.duracionDisney;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------

public String toString() { 
   return "ListadoIncidenciasDisponibilidadLlamadasRegularizada  ["+
    						",datosCobre  ="+ datosCobre +
    						",datosFibra  ="+ datosFibra +
    						",voz  ="+ voz +
    						",vozIp  ="+ vozIp +
    						",tvCobre  ="+ tvCobre +
    						",tvFibra  ="+ tvFibra +
    						",tv  ="+ tv +
    						",mfe  ="+ mfe +
    						",dth  ="+ dth +
    						",ott  ="+ ott +
    						",netflix  ="+ netflix +
    						",disney  ="+ disney +
    						",clieDatosCobre  ="+ clieDatosCobre +
    						",clieDatosFibra  ="+ clieDatosFibra +
    						",clieVoz  ="+ clieVoz +
    						",clieVozIp  ="+ clieVozIp +
    						",clieTvCobre  ="+ clieTvCobre +
    						",clieTvFibra  ="+ clieTvFibra +
    						",clieTv  ="+ clieTv +
    						",clieMfe  ="+ clieMfe +
    						",clieDth  ="+ clieDth +
    						",clieOtt  ="+ clieOtt +
    						",clieNetflix  ="+ clieNetflix +
    						",clieDisney  ="+ clieDisney +
    						",duracionDatosCobre  ="+ duracionDatosCobre +
    						",duracionDatosFibra  ="+ duracionDatosFibra +
    						",duracionVoz  ="+ duracionVoz +
    						",duracionVozIp  ="+ duracionVozIp +
    						",duracionTvCobre  ="+ duracionTvCobre +
    						",duracionTvFibra  ="+ duracionTvFibra +
    						",duracionTv  ="+ duracionTv +
    						",duracionMfe  ="+ duracionMfe +
    						",duracionDth  ="+ duracionDth +
    						",duracionOtt  ="+ duracionOtt +
    						",duracionNetflix  ="+ duracionNetflix +
    						",duracionDisney  ="+ duracionDisney +"]";

}
}
